### ISSUE TITLE
List Tron (TRX) on SevenGrids

### ISSUE THREAD

**Issue by cryptorexit** [sevengrids/android-app#1]
Hello guys. I was wondering if you have in mind listing Tron on SevenGrids Wallet. It seems to me that Tron is one of the most popular cryptocurrencies and many of us are waiting for it to be listed on 7G. Thank you.

**Comment by sevengrids-dev** [comment]
@cryptorexit We are currently working to list Tron on [SevenGrids](https://sevengrids.com). We hope it will be listed on November 23, 2020.
